version: '3.9'

services:

  db:
    env_file:
      - .env
    container_name: pg_db
    image: postgres:15.0
    restart: always
    volumes:
      - ./init-multi-postgres-databases.sh:/docker-entrypoint-initdb.d/init-multi-postgres-databases.sh
    ports:
      - "5432:5432"

  pgadmin:
    env_file:
      - .env
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "16543:80"

  gpt:
    env_file:
      - .env
    container_name: gpt
    image: meacronics/skills_guide_gpt:latest
    restart: always
    ports:
      - "7000:7000"

  parser:
    env_file:
      - .env
    container_name: parser
    image: te
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db

  telegram:
    env_file:
      - .env
    container_name: telegram
    image: meacronics/skills_guide_telegram:latest
    restart: always
    ports:
      - "6000:6000"
    depends_on:
      - parser

  site:
    env_file:
      - .env
    container_name: site
    image: meacronics/skills_guide_site:latest
    restart: always
    ports:
      - "80:8000"
    depends_on:
      - parser
